server:
  port: 8083

spring:
  application:
    name: fitworkup-api

app:
  jwt:
    secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
    expiration-ms: ${JWT_EXPIRATION_MS:86400000}
    expiration-in-ms: ${JWT_EXPIRATION_MS:86400000}
  
  # 📧 CONFIGURAÇÃO DE E-MAIL (Redefinição de Senha)
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:redefinirsenhasystem6@gmail.com}
    password: ${MAIL_PASSWORD:fcvh fwwg bdcd uzms}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  # 🌐 CONFIGURAÇÃO DO GOOGLE SIGN-IN (OAuth2)
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:SEU_CLIENT_ID_AQUI.apps.googleusercontent.com}
            client-secret: ${GOOGLE_CLIENT_SECRET:SUA_CLIENT_SECRET_AQUI}
            scope:
              - profile
              - email

  # Definição de qual perfil rodará por padrão
  profiles:
    active: dev